/* Optional teaching prototype. All examples/data are fictional; no storage or network calls. */
const slides = [
  {
    lesson:"PART 1 · THE RULE",title:"The result on your screen was chosen",lead:"Three school-club posts are available. Which one should appear first?",
    visual:`<div class="score-grid"><div class="score-card"><span class="tag">A</span><strong>Concert</strong><span>12 views · new club</span></div><div class="score-card"><span class="tag">B</span><strong>Science demo</strong><span>5 views · recent</span></div><div class="score-card"><span class="tag">C</span><strong>Sports update</strong><span>40 views · older</span></div></div><p class="muted-note">The cards and figures are fictional. Nothing is ranked yet.</p>`,
    side:"Popularity, recency and a chance for new clubs lead to different orders. Before seeing a formula, name the objective you would choose and who might gain or lose visibility.",question:"What information would your rule need as input?",notes:"A feed is not simply a pile of posts. It is an ordered result. Ask students to vote silently for the first card and explain which information they used. Do not reveal a right choice. The objective is a human decision. Today we will make the rule traceable before we examine its social consequences.",source:"Textbook §3.2, p. 81; fictional school-feed example."},
  {
    lesson:"PART 1 · THE RULE",title:"Input → instructions → output",lead:"An algorithm is a sequence of steps for a task. Make each part visible before judging the result.",stages:3,
    visual:`<div class="steps"><div class="node stage" data-stage="1"><strong>Input</strong><small>Available cards and measurements</small></div><span class="arrow stage" data-stage="2" aria-hidden="true">→</span><div class="node stage" data-stage="2"><strong>Rule</strong><small>Compare, select, order</small></div><span class="arrow stage" data-stage="3" aria-hidden="true">→</span><div class="node stage" data-stage="3"><strong>Output</strong><small>One ordered feed</small></div></div>`,
    side:"An algorithm can be written in ordinary language and followed by a person. Code implements a procedure; the words algorithm and AI are not interchangeable.",question:"Which part would you inspect if the same club appears first every day?",notes:"Reveal each stage only after students name it. Input may include data about cards; the rule compares and orders them; the output is the feed. Ask students whether repeated prominence could come from the data, the rule, or both. Do not claim the model reflects a real platform.",source:"Textbook §3.2A–C, pp. 81–83; original diagram."},
  {
    lesson:"PART 1 · THE RULE",title:"A usable rule leaves less to guess",lead:"Compare an ambiguous instruction with a traceable one.",
    visual:`<div class="contrast"><div class="weak"><h3>Ambiguous</h3><p class="statement">“Show the best post.”</p><p>Best for whom? What if two posts tie?</p></div><div class="strong"><h3>Traceable</h3><p class="statement">“Sort by score. Break ties by card ID.”</p><p>Every input gets a defined order.</p></div></div>`,
    side:"A usable procedure has clear steps, a defined output and a stopping point. It must be feasible with the available data and resources.",question:"What missing instruction would make “best post” runnable by two different people in the same way?",notes:"Have two students interpret best post before showing the right-hand card. Ask if the revised rule stops and what would happen with missing data. The chapter also calls algorithm steps independent of the programming language used to implement them.",source:"Textbook §3.2A, pp. 81–82; original contrast."},
  {
    lesson:"PART 1 · THE RULE",title:"A conditional makes a decision",lead:"A rule can branch when a value crosses a threshold.",stages:2,
    visual:`<div class="formula">IF completion ≥ 60%<br>THEN mark “finished”<br>ELSE mark “unfinished”</div><div class="demo-row stage" data-stage="1"><label for="completion">Choose completion rate: <output id="completion-value">45%</output></label><input id="completion" type="range" min="0" max="100" value="45" step="5" aria-describedby="threshold-help"></div><div id="threshold-result" class="test-result stage" data-stage="2" role="status">Move the slider, then reveal the decision.</div><p class="muted-note" id="threshold-help">Original practice rule, not a real platform policy.</p>`,
    side:"The boundary matters. A value of 60% passes because the rule says ≥, not >. A different threshold could change the output without changing the student's behaviour.",question:"Predict the result at 55%, 60% and 65% before moving the slider.",notes:"Freeze at 55 and ask whether it reaches the threshold. Reveal the result. Repeat at 60 and 65. Ask who chose 60 and what the model cannot tell us about whether this is a good measure of learning. This is a parallel practice case, not the assessed Loopline task.",source:"Textbook §3.2B, p. 83; original synthetic threshold example."},
  {
    lesson:"PART 1 · THE RULE",title:"A loop needs a stop",lead:"Search a short list one card at a time. The process ends when the target is found or the list ends.",stages:4,
    visual:`<div class="steps"><div class="node stage" data-stage="1"><strong>1</strong><small>Concert</small></div><div class="node stage" data-stage="2"><strong>2</strong><small>Science demo</small></div><div class="node stage" data-stage="3"><strong>3</strong><small>Sports update</small></div><div class="node stage" data-stage="4"><strong>STOP</strong><small>List exhausted</small></div></div><p class="muted-note">Target: Drama rehearsal. There is no match in this fictional list.</p>`,
    side:"Each pass checks one item. If we reach the end with no match, the procedure still needs a defined output: “not found.” Searching, sorting, filtering and counting solve different problems.",question:"What happens if the stop condition is missing?",notes:"Students trace the four stages aloud. Ask what changes if Drama rehearsal is inserted second. The loop is finite because the list is finite and the position advances. Follow with the existing search/sort simulation only after a hand trace on different cards.",source:"Textbook §3.2B–D, pp. 83–85; original synthetic list."},
  {
    lesson:"PART 1 · CHECK",title:"Retrieve before you look back",lead:"Three short checks reveal whether the procedure makes sense—not just whether the words sound familiar.",
    visual:`<div class="check-options" data-check="algorithm"><button type="button" data-choice="a">An algorithm is always an AI model.</button><button type="button" data-choice="b">An algorithm is a sequence of steps for a task.</button><button type="button" data-choice="c">An algorithm is the outcome of a decision.</button></div><p class="feedback" role="status" aria-live="polite"></p><a class="link-button" href="../sim/search-sort.html">Open the existing search/sort simulation after a hand trace ↗</a>`,
    side:"Work individually first. Then explain the input, rule and stop condition in the search example. Return to the chapter or transcript to repair a missed idea.",question:"Why can code express an algorithm without making every algorithm AI?",notes:"Choose the statement that names what an algorithm is. After answering, explain why the other two statements are too broad or confuse a rule with its result. This is practice, not a grade.",source:"Textbook §3.2A–D, pp. 81–85; original formative question."},
  {
    lesson:"PART 2 · THE VALUE",title:"A ranking rule is a value choice",lead:"Same three cards. This time we can see the equation.",stages:2,
    visual:`<div class="formula">score = 2 × relevance + novelty</div><div class="score-grid stage" data-stage="1"><div class="score-card" data-card="A"><span class="tag">A · Concert</span><strong>?</strong><span>relevance 2 · novelty 3</span></div><div class="score-card" data-card="B"><span class="tag">B · Science</span><strong>?</strong><span>relevance 3 · novelty 1</span></div><div class="score-card" data-card="C"><span class="tag">C · Sports</span><strong>?</strong><span>relevance 1 · novelty 2</span></div></div><p class="muted-note stage" data-stage="2">Calculate by hand first. Then reveal the scores and top card.</p>`,
    side:"Relevance counts twice as much as novelty. That choice is built into the equation. It may serve the viewer's known interests and reduce discovery of unfamiliar clubs.",question:"Calculate A, B and C. Which wins, and whose value does the rule favour?",notes:"Calculate all three scores on paper. If two cards tie, use the card ID as the tie breaker. Notice that the output depends on both the card data and the chosen weight. A toy score does not describe any real recommender.",source:"Textbook §3.2D–E, pp. 84–86; fictional ranking model."},
  {
    lesson:"PART 2 · THE VALUE",title:"Change one weight; watch the order move",lead:"Keep the cards fixed. Adjust only the value placed on novelty.",stages:1,
    visual:`<div class="demo-row"><label for="novelty">Novelty weight: <output id="novelty-value">1</output></label><input id="novelty" type="range" min="0" max="3" value="1" step="1" aria-describedby="rank-help"></div><div class="score-grid" id="rank-cards"><div class="score-card" data-rank="A"><span class="tag">A · Concert</span><strong>7</strong><span>2×2 + 1×3</span></div><div class="score-card" data-rank="B"><span class="tag">B · Science</span><strong>7</strong><span>2×3 + 1×1</span></div><div class="score-card" data-rank="C"><span class="tag">C · Sports</span><strong>4</strong><span>2×1 + 1×2</span></div></div><p class="muted-note" id="rank-help">Tie breaker: card ID A before B before C. Scores and order update after Reveal.</p>`,
    side:"Predict the new top card before pressing Reveal. Keep the data fixed: then a changed order can be attributed to this changed rule within the toy model.",question:"Which card rises when novelty receives more weight? What does this comparison NOT prove about a real platform?",notes:"Predict the first card when novelty has no weight. Reveal the result, then increase the novelty weight and compare again. The cards stay the same; only one number in the rule changes. Explain the change within this simplified model before saying anything about a real platform.",source:"Textbook §3.2D–E, pp. 84–86; original synthetic model."},
  {
    lesson:"PART 2 · THE SYSTEM",title:"An output becomes the next input",lead:"Recommendation can form a feedback loop when exposure changes behaviour and that behaviour is logged.",stages:4,
    visual:`<div class="flow"><div class="node stage" data-stage="1"><strong>Show</strong><small>Which card is seen?</small></div><div class="node stage" data-stage="2"><strong>Act</strong><small>Watch, skip or click</small></div><div class="node stage" data-stage="3"><strong>Log</strong><small>Record a signal</small></div><div class="node stage" data-stage="4"><strong>Rank again</strong><small>Future feed changes</small></div></div><div class="formula stage" data-stage="4">exposure → action → data → ranking → exposure</div>`,
    side:"The loop can amplify what is already visible. But a click is not a complete account of preference, intent or satisfaction. Human choices enter through what is shown, measured and optimized.",question:"Pause before Log: What information would the platform actually have, and what would it still not know?",notes:"Reveal one stage at a time. Freeze after action: ask whether a click means approval, curiosity or accidental opening. After rank again, ask students who defines the objective and where a small initial difference might accumulate. This is a conceptual loop, not a quantified claim about a real platform.",source:"Textbook §3.2E, pp. 86–89; original conceptual diagram."},
  {
    lesson:"PART 2 · THE DILEMMA",title:"Where can unfairness enter?",lead:"Look for a specific input, proxy, objective or feedback step—not a vague label.",stages:3,
    visual:`<div class="flow"><div class="node stage" data-stage="1"><strong>Data</strong><small>Whose history is present?</small></div><div class="node stage" data-stage="2"><strong>Proxy</strong><small>Does it measure the real need?</small></div><div class="node stage" data-stage="3"><strong>Rule</strong><small>Which outcome is rewarded?</small></div><div class="node stage" data-stage="3"><strong>Review</strong><small>Who can challenge it?</small></div></div><p class="muted-note">Fictional library queue: frequent borrowers get faster help. A new student has no history.</p>`,
    side:"Efficiency may improve for frequent borrowers, yet the chosen proxy can disadvantage a person with little recorded history. Ask what evidence would show a real disadvantage before making a claim about an institution.",question:"Which *specific* design choice might exclude the new student? What different objective could the library choose?",notes:"Distinguish data gap, proxy choice, objective and appeals process. The textbook discusses bias, opaque systems and responsibility; avoid telling students every algorithm is biased or that a toy example proves harm. This is a parallel case for thinking, not a real case study.",source:"Textbook §3.2E, pp. 86–89; fictional library example."},
  {
    lesson:"PART 2 · CHECK",title:"Separate a model from evidence",lead:"A simplified model can explain a possibility. It cannot by itself establish a real-world effect.",
    visual:`<div class="check-options" data-check="evidence"><button type="button" data-choice="a">The toy model proves that real feeds disadvantage new creators.</button><button type="button" data-choice="b">The toy model shows how changing a weight can change an order under stated assumptions.</button><button type="button" data-choice="c">A transparent rule cannot create unfair outcomes.</button></div><p class="feedback" role="status" aria-live="polite"></p><a class="link-button" href="../sim/tune-the-feed.html">Open the existing Tune the Feed simulation after a hand calculation ↗</a>`,
    side:"For a real claim, examine the platform's documentation and independent evidence. Ask what was measured, whose perspective is missing and whether an alternative explanation fits.",question:"Write one limitation of the school-feed model and one source you would need for a real-world inquiry.",notes:"Decide which statement stays within what the toy model can show. A fictional calculation can illustrate a possible mechanism. It cannot by itself establish that a real platform caused a social effect. Name one thing you would need to investigate a real case.",source:"Textbook §3.2E, pp. 86–89; original formative question."},
  {
    lesson:"PART 2 · REAL CASE",title:"A different feed is a real policy choice",lead:"The EU requires designated very large platforms and search engines to offer a recommender option that is not based on user profiling.",stages:2,
    visual:`<div class="contrast"><div class="stage" data-stage="1"><h3>Profile-based option</h3><p class="statement">Past activity may shape what appears next.</p><p>The platform chooses which signals and objective matter.</p></div><div class="stage" data-stage="2"><h3>Non-profiling option</h3><p class="statement">Recommendation without a user profile.</p><p>This still needs a rule; it does not mean there is no algorithm.</p></div></div><p class="muted-note">Simplified comparison of two design approaches, not a depiction of any platform's actual feed.</p>`,
    side:"The Digital Services Act responds to a question of power and transparency: what choices should users have over recommender systems? The legal requirement does not establish that a particular algorithm is fair or that one option is always better.",question:"Which part of the textbook dilemma does this policy address? What evidence would you need to judge its effect for users?",notes:"In the earlier toy model, a weight changed which card appeared first. A real recommender has many more inputs and decisions. The European Commission says designated very large online platforms and search engines must offer at least one recommendation option not based on profiling. Compare the possible choices, then ask what information would show whether the option works well in practice. A policy requirement is evidence of a response to a dilemma, not evidence that every platform outcome is solved.",source:"Current layer · European Commission, Digital Services Act VLOP/VLOSE obligations (checked 7 Oct 2026).",link:"https://digital-strategy.ec.europa.eu/en/policies/dsa-vlops"
  },
  {
    lesson:"PART 2 · TRANSFER",title:"Explain a changed rule without the animation",lead:"A fictional help desk now prioritizes tickets by urgency and waiting time.",
    visual:`<table class="mini-table"><thead><tr><th>Ticket</th><th>Urgency</th><th>Wait (hours)</th></tr></thead><tbody><tr><td>A · locked account</td><td>3</td><td>1</td></tr><tr><td>B · printer issue</td><td>1</td><td>5</td></tr><tr><td>C · lost document</td><td>2</td><td>2</td></tr></tbody></table><p class="prompt-box">Old rule: score = 2 × urgency + wait. New rule: score = 4 × urgency + wait. Highest first; break ties by ticket ID.</p>`,
    side:"No Coach or answer reveal here. Work independently, then compare your trace with teacher feedback in the existing lesson route. This is formative practice, not a new registered assessment.",question:"Calculate both orders. Explain who moves, why, one trade-off, and one limitation of the rule.",notes:"Keep your first calculation and explain what changed when urgency received more weight. Identify the ticket whose place changes. Then ask whether urgency and waiting time alone capture all the information a human help-desk worker would need. This is separate from the registered scored tasks.",source:"Textbook §3.2A–E, pp. 81–89; original synthetic changed-case task."}
];

let index=0, stage=0, speech=null, paused=false;
const $=id=>document.getElementById(id);
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function stopSpeech(){if('speechSynthesis' in window)window.speechSynthesis.cancel();speech=null;paused=false;$('audio-status').textContent='';$('speak').textContent='▶ Read aloud';}
function updateStages(){document.querySelectorAll('[data-stage]').forEach(el=>el.classList.toggle('on',Number(el.dataset.stage)<=stage));$('reveal').hidden=!slides[index].stages;$('reveal').disabled=!slides[index].stages||stage>=slides[index].stages;$('reveal').textContent=!slides[index].stages?'No staged reveal':stage>=slides[index].stages?'All stages shown':`Reveal stage ${stage+1}`;if(index===3)updateThreshold();if(index===6&&stage>=2)updateBasicScores();if(index===7)updateRanking();}
function updateThreshold(){const input=$('completion');if(!input)return;const n=Number(input.value);$('completion-value').textContent=`${n}%`;const result=$('threshold-result');result.textContent=stage>=2?`${n}% → ${n>=60?'FINISHED':'UNFINISHED'}`:'Move the slider, then reveal the decision.';}
function updateBasicScores(){for(const [id,score] of [['A',7],['B',7],['C',4]]){const card=document.querySelector(`[data-card="${id}"]`);if(card)card.querySelector('strong').textContent=String(score);}document.querySelector('[data-card="A"]')?.classList.add('winner');}
function updateRanking(){
  if(index!==7)return;
  const weight=Number($('novelty').value);
  $('novelty-value').textContent=String(weight);
  const data={A:{name:'Concert',relevance:2,novelty:3},B:{name:'Science',relevance:3,novelty:1},C:{name:'Sports',relevance:1,novelty:2}};
  const container=$('rank-cards');
  const rows=Object.keys(data).map(id=>({id,score:2*data[id].relevance+weight*data[id].novelty}));
  if(stage>=1)rows.sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));
  else rows.sort((a,b)=>a.id.localeCompare(b.id));
  const first=new Map([...container.children].map(card=>[card.dataset.rank,card.getBoundingClientRect()]));
  rows.forEach((row,position)=>{
    const card=container.querySelector(`[data-rank="${row.id}"]`);
    card.querySelector('strong').textContent=stage>=1?String(row.score):'?';
    card.querySelector('.tag').textContent=stage>=1?`${position+1} · ${row.id} · ${data[row.id].name}`:`${row.id} · ${data[row.id].name}`;
    card.querySelector('span:last-child').textContent=`2×${data[row.id].relevance} + ${weight}×${data[row.id].novelty}`;
    card.classList.toggle('winner',stage>=1&&position===0);
    container.appendChild(card);
  });
  if(stage>=1&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){
    [...container.children].forEach(card=>{
      const before=first.get(card.dataset.rank),after=card.getBoundingClientRect();
      const dx=before.left-after.left,dy=before.top-after.top;
      if(dx||dy)card.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:520,easing:'ease-out'});
    });
  }
}
function render(){stopSpeech();const s=slides[index];stage=0;$('position').textContent=`${index+1} / ${slides.length}`;$('progress-fill').style.width=`${(index+1)/slides.length*100}%`;$('slide').innerHTML=`<p class="eyebrow">${escapeHtml(s.lesson)} · SLIDE ${String(index+1).padStart(2,'0')}</p><h1 class="slide-title">${escapeHtml(s.title)}</h1><p class="lead">${escapeHtml(s.lead)}</p><div class="layout"><section class="visual" aria-label="Instructional visual">${s.visual}</section><aside class="side"><h2>Think it through</h2><p>${escapeHtml(s.side)}</p><div class="question"><h2>Pause and respond</h2><p>${escapeHtml(s.question)}</p></div><p class="source">${escapeHtml(s.source)}${s.link?` <a href="${escapeHtml(s.link)}" target="_blank" rel="noopener">Open primary source ↗</a>`:''}</p></aside></div><details class="transcript"><summary>Read the full narration</summary><p>${escapeHtml(s.notes)}</p></details>`;$('back').disabled=index===0;$('next').disabled=index===slides.length-1;updateStages();bindSlide();$('slide').focus({preventScroll:true});history.replaceState(null,'',`#slide-${String(index+1).padStart(2,'0')}`);}
function bindSlide(){const completion=$('completion');if(completion)completion.addEventListener('input',updateThreshold);const novelty=$('novelty');if(novelty)novelty.addEventListener('input',()=>{stage=0;updateStages();});document.querySelectorAll('[data-check] button').forEach(btn=>btn.addEventListener('click',()=>{const wrapper=btn.closest('[data-check]');const right='b';wrapper.querySelectorAll('button').forEach(x=>x.removeAttribute('data-result'));btn.dataset.result=btn.dataset.choice===right?'right':'wrong';wrapper.nextElementSibling.textContent=btn.dataset.choice===right?'Yes. Explain why in your own words.':'Try again. Revisit the input → rule → output chain and the model limitation.';}));}
function change(delta){const n=Math.max(0,Math.min(slides.length-1,index+delta));if(n!==index){index=n;render();}}
$('back').addEventListener('click',()=>change(-1));$('next').addEventListener('click',()=>change(1));$('reveal').addEventListener('click',()=>{stage=Math.min(slides[index].stages||0,stage+1);updateStages();});
$('speak').addEventListener('click',()=>{if(!('speechSynthesis' in window)){$('audio-status').textContent='Speech unavailable; use transcript.';return;}if(paused){window.speechSynthesis.resume();paused=false;$('audio-status').textContent='Reading';return;}stopSpeech();speech=new SpeechSynthesisUtterance(slides[index].notes);speech.lang='en-CA';speech.rate=.92;speech.onend=()=>{$('audio-status').textContent='Finished';speech=null;};speech.onerror=()=>{$('audio-status').textContent='Use transcript';speech=null;};window.speechSynthesis.speak(speech);$('audio-status').textContent='Reading';});
$('pause').addEventListener('click',()=>{if(speech&&'speechSynthesis' in window){window.speechSynthesis.pause();paused=true;$('audio-status').textContent='Paused';}});$('stop').addEventListener('click',stopSpeech);
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','BUTTON','A'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight'){change(1);}else if(e.key==='ArrowLeft'){change(-1);}else if(e.key.toLowerCase()==='r'&&slides[index].stages){stage=Math.min(slides[index].stages,stage+1);updateStages();}});
const match=location.hash.match(/^#slide-(\d{1,2})$/);if(match)index=Math.max(0,Math.min(slides.length-1,Number(match[1])-1));render();
