"use strict";

// Student-facing additions only. Assessed questions, task IDs and lesson IDs remain in index.html.
const commonChecklist = ["Recall the mechanism before opening any support", "Complete the hand-worked model", "Record evidence in the matching response box", "Check the causal link before moving on"];
const commonFrames = ["The service depends on… because…", "The evidence shows… which suggests…", "An alternative explanation is…", "This matters for… because…"];
function support(today, glossary, summary, workedTitle, workedText, stretch) {
  return {today, glossary, summary, checklist: commonChecklist, worked:{title:workedTitle,text:workedText}, frames:commonFrames, stretch};
}

window.SPRINT04_EXPERIENCE = {
  studentOsUrl: "https://script.google.com/a/macros/gnspes.ca/s/AKfycby3lAqgW184t9EnOZg2XHDh6C8jYGZUBFpXeLICFZnAu0Yrkab3hcw6QFboHR7FWVTo/exec#/journal",
  hook: {
    lesson: "d01",
    title: "The building is open. Is the library open?",
    prompt: "The doors, lights and reading rooms work, but the catalogue, ordering, email and reader accounts do not. Vote before reading the case.",
    options: ["The library is open", "The library is closed", "It depends on the user and task"],
    followUp: "Name one person whose answer would differ from yours and the dependency that changes their answer."
  },
  videos: [
    {
      lesson:"d03", title:"The hidden network that makes the internet possible", channel:"TED-Ed · Sajan Saini", url:"https://www.ted.com/talks/sajan_saini_the_hidden_network_that_makes_the_internet_possible", length:"5:08", watch:"0:00–3:48 (3:48)", captions:"TED transcript and captions available", questions:["What physical path carries the signal?","Where could capacity become a bottleneck?","Which part is invisible to an ordinary user?"], after:"Connect one physical network component in the clip to a hop in Harbourview’s hand-worked packet route."
    },
    {
      lesson:"d04", title:"Compression", channel:"Computerphile · David Brailsford", url:"https://www.youtube.com/watch?v=Lto-ajuqW3w", length:"7:18", watch:"0:00–4:36 (4:36)", captions:"YouTube captions available", questions:["What repeated information can be represented more compactly?","What must the receiver know to rebuild the original?","When would losing detail be unacceptable?"], after:"Explain whether your hand-worked run-length example is lossless and what evidence proves it."
    },
    {
      lesson:"d06", title:"Discover the physical side of the internet", channel:"TED · Andrew Blum", url:"https://www.ted.com/talks/andrew_blum_discover_the_physical_side_of_the_internet", length:"11:59", watch:"0:34–4:32 (3:58)", captions:"TED transcript and captions available", questions:["Which physical dependencies make a digital service fragile?","Who owns or controls the places shown?","What would a recovery team need to restore first?"], after:"Add one physical dependency and one ownership boundary to your recovery-priority reasoning."
    },
    {
      lesson:"d09", title:"A Magna Carta for the web", channel:"TED · Tim Berners-Lee", url:"https://www.ted.com/talks/tim_berners_lee_a_magna_carta_for_the_web", length:"6:47", watch:"0:00–4:20 (4:20)", captions:"TED transcript and captions available", questions:["How does the speaker distinguish the web from its underlying network?","Which design values are at stake?","Where does human oversight enter?"], after:"Write one oversight question that links a technical decision to access, openness or control."
    }
  ],
  simulations: [
    {lesson:"d03", heading:"Lab", name:"Send a Packet", sourceName:"S4 · Packets and protocols", status:"Built and locally checked. Offline; no login or data collection.", href:"sim/send-a-packet.html", directions:"Complete the human packet route and calculate the rounds by hand first. Then use the simulation with its separate synthetic route.", returnQuestion:"What changed when a route or capacity changed, and which protocol rule still had to hold?"},
    {lesson:"d04", heading:"Lab", name:"Squeeze and Seal", sourceName:"S4 · Compression and security", status:"Built and locally checked. Offline; no login or data collection.", href:"sim/squeeze-and-seal.html", directions:"Complete the hand-worked compression and protection comparison first. Then test the separate synthetic messages.", returnQuestion:"Which operation reduced size, which protected meaning, and why are those different jobs?"},
    {lesson:"d06", heading:"Lab", name:"Restore the Service", sourceName:"S4 · Backups and recovery", status:"Built and locally checked. Offline; no login or data collection.", href:"sim/restore-the-service.html", directions:"Build both recovery schedules by hand before opening this model. The simulation uses a different synthetic service set.", returnQuestion:"Which dependency forced the earliest possible return time, and who gained from your priority rule?"}
  ],
  discussion: {
    lesson:"d07", mode:"debate", respondFirst:true, title:"Who should return first?", stimulus:{label:"British Library cyber-incident review",url:"https://www.bl.uk/home/british-library-cyber-incident-review-8-march-2024.pdf"}, prompt:"After a cyber incident, should an institution restore the service used by the greatest number of people first, even when a smaller service carries a legal or safety duty?", positions:["Yes — broad public access should lead","No — legal and safety duties should lead","Use a published conditional rule rather than one fixed priority"], reply:"Reply to one classmate by naming a dependency or stakeholder their rule handles well, then one case that could force the rule to change."
  },
  choice: {lesson:"d08",title:"Choose the transfer lens",note:"This is an unscored rehearsal before the locked independent hospital task.",contexts:["School learning platform","Local pharmacy booking service","Community transit card"],prompt:"For your chosen service, diagnose one plausible failure from evidence, name an alternative, and justify the first restoration priority. The reasoning standard stays the same in every context."},
  selfChecks: {
    d02:[{q:"Which component executes instructions?",options:["CPU","SSD","Router"],answer:0,why:"The CPU executes program instructions; storage retains data and a router moves packets."},{q:"Which storage is normally volatile?",options:["RAM","SSD","Backup tape"],answer:0,why:"RAM normally loses its contents when power is removed."},{q:"An input becomes useful information after it is…",options:["processed in context","copied twice","sent online"],answer:0,why:"Processing and context give data meaning."}],
    d03:[{q:"A packet header mainly carries…",options:["addressing and control information","the entire website","a password"],answer:0,why:"Headers guide delivery and reassembly."},{q:"A protocol is…",options:["an agreed communication rule","a physical cable","a company"],answer:0,why:"Protocols define how communicating systems behave."},{q:"A bottleneck changes delivery because…",options:["one hop has less capacity","every packet changes meaning","addresses disappear"],answer:0,why:"The lowest-capacity dependency constrains flow."}],
    d04:[{q:"Lossless compression means…",options:["the original can be reconstructed exactly","the file is encrypted","some detail is removed"],answer:0,why:"Lossless methods preserve all original information."},{q:"Encryption primarily protects…",options:["confidentiality","file size","network speed"],answer:0,why:"Encryption makes content unreadable without the required key."},{q:"A backup helps only if it is…",options:["usable during recovery","stored beside the original only","never tested"],answer:0,why:"Recovery needs a valid, accessible and tested copy."}],
    d05:[{q:"A 503 response most directly indicates…",options:["the service is unavailable","the name cannot resolve","the client has no address"],answer:0,why:"503 is an application/service response, so the request reached a responding server layer."},{q:"A strong outage explanation links…",options:["mechanism, evidence and consequence","only a definition","only a stakeholder opinion"],answer:0,why:"Causal explanation needs all three."},{q:"One observation can…",options:["support more than one diagnosis","prove every cause","replace missing evidence"],answer:0,why:"Alternatives remain until evidence discriminates between them."}],
    d07:[{q:"Synthesis is strongest when organized by…",options:["shared themes and relationships","one source at a time","quotation length"],answer:0,why:"Theme-based comparison makes agreement, difference and explanation visible."},{q:"A source limitation should be…",options:["connected to the claim you use","a generic insult","ignored if official"],answer:0,why:"Authority does not remove purpose, timing or evidence limits."},{q:"Provisional figures should be…",options:["labelled provisional","rounded into certainty","removed"],answer:0,why:"The status of evidence travels with the claim."}],
    d09:[{q:"The web is…",options:["a service using the internet","the same as every network","a physical router"],answer:0,why:"The web uses internet infrastructure and protocols; it is not the whole internet."},{q:"Human oversight is strongest when the reviewer has…",options:["timely evidence and authority to act","only an alert","no stated responsibility"],answer:0,why:"A human must be able to understand and intervene."},{q:"A defensible causal claim includes…",options:["evidence and uncertainty","certainty without evidence","only chronology"],answer:0,why:"Sequence alone does not establish cause."}]
  },
  supports: {
    start:support("Preview the sprint route, safety boundary and evidence expectations.",[["dependency","A component or service another service needs."],["system boundary","The line between what an organization controls and what another provider controls."],["public service","A service intended to meet a community need."]],"This sprint traces how computing, networks, security and recovery decisions affect public access. All practical cases are synthetic and safe.","Community pool booking","A booking site can fail while the physical pool stays open. Map users, booking software, identity provider and payment service before deciding whether the service is available.",["Which dependency in the sprint could create the widest social consequence?","How could two stakeholders define ‘restored’ differently?"]),
    d01:support("Map a service as people, technologies, organizations and dependencies.",[["standalone","A device operating without a network dependency."],["networked computing","Devices sharing data or services through a network."],["cloud provider","An outside organization running computing resources for a client."]],"A building may remain open while digital services fail because each service relies on a chain of local and external components.","School lunch account","A lunch account needs the student record, reader, network and payment provider. If the provider fails, a paper list can preserve access while payment is delayed.",["Add one hidden dependency to your map and justify it.","Identify one dependency the library cannot control directly."]),
    d02:support("Trace input, processing, memory, storage and output inside one computing task.",[["CPU","The component that executes instructions."],["RAM","Fast working memory, usually volatile."],["secondary storage","Longer-term non-volatile storage such as an SSD."]],"A computing task moves data through components with distinct roles. A fault’s location changes the visible symptom and the recovery action.","Photo kiosk","A kiosk reads an image from storage into RAM, the CPU transforms pixels, then the display shows the result. A full disk and insufficient RAM create different symptoms.",["How would the trace change if the application used remote storage?","Which component failure could look like a software fault?"]),
    d10:support("Model how limited memory or slow storage affects a service request.",[["paging","Moving memory pages between RAM and storage."],["latency","Delay before a result or transfer completes."],["throughput","Amount processed or transferred per unit of time."]],"When working data exceeds available RAM, storage may temporarily support memory. Because storage is slower, the whole service can become delayed.","Video editor","A video project needs 10 GB of active data but has 8 GB of free RAM, so 2 GB may page to storage. The work continues, but response time rises.",["Change one capacity value and predict the user-visible effect.","Explain why adding storage space does not always fix slow paging."]),
    d03:support("Route packets by hand, calculate capacity effects, then open Send a Packet.",[["packet","A formatted unit of data sent through a network."],["router","A device that forwards packets between networks."],["protocol","An agreed rule for formatting and exchanging data."]],"Data is divided into packets that carry addressing and control information. Each hop and capacity limit affects delivery, while protocols support ordering and reassembly.","Museum ticket request","Six packets cross a three-hop route. A one-packet-per-round middle hop determines the fastest completion even if the other links can carry two.",["What evidence would distinguish packet loss from delay?","How could rerouting improve resilience but increase latency?"]),
    d11:support("Use addressing, DNS, routing and service responses to distinguish three failures.",[["DNS","The naming system that maps domain names to addresses."],["routing table","Rules used to select a packet’s next hop."],["HTTP status","A web server’s coded response to a request."]],"A failed name lookup, missing route and unavailable application produce different evidence. Diagnose the layer before proposing a repair.","Community theatre","If the domain resolves but no route exists, changing the website code cannot restore reachability. If a 503 returns, the network path worked far enough to reach a service layer.",["Create one ambiguous symptom and name the extra test required.","Which diagnosis would be most harmful if acted on incorrectly?"]),
    d04:support("Separate compression, encryption, access control, integrity and backup; then open Squeeze and Seal.",[["compression","Representing data with fewer bits."],["encryption","Transforming data so an authorized key is needed to read it."],["integrity","Confidence that data has not been altered improperly."]],"Security and protection controls do different jobs. A smaller file is not automatically secret, and an encrypted file is not automatically recoverable.","Sports club roster","Run-length encoding can shrink repeated attendance codes. Encryption protects member details in transit. A tested backup supports recovery; none replaces the others.",["Choose two controls and explain a gap that remains.","When could compression increase a privacy risk rather than reduce it?"]),
    d05:support("Use quiz feedback, then build a mechanism → evidence → stakeholder consequence explanation.",[["diagnosis","An evidence-based explanation of a fault."],["causal link","A reasoned connection between mechanism and consequence."],["alternative","Another explanation that could fit some evidence."]],"A strong outage explanation identifies the failed layer, cites discriminating evidence and traces the effect to a person or service.","Clinic printer queue","Jobs reach the print server but remain queued. That evidence weakens a network-disconnection claim and supports a service or device-capacity diagnosis.",["What evidence would overturn your preferred diagnosis?","Add a stakeholder who experiences an indirect consequence."]),
    d06:support("Classify source claims and build two recovery schedules by hand before Restore the Service.",[["reported fact","An observation or record stated by the source."],["inference","A conclusion drawn from evidence."],["recovery dependency","A prerequisite that must return before another service can."]],"Recovery order reflects dependencies and values. Source status matters: reported facts, inference and uncertainty cannot be treated as equal proof.","Municipal recreation portal","Identity must return before registration; validated backups must return before old bookings. A two-team schedule can prioritize public signup or record integrity, producing different winners.",["Design a third priority rule and test its return dates.","Which missing fact would most change your recommendation?"]),
    d07:support("Synthesize the library and hospital sources by continuity, cost and trust.",[["synthesis","Combining sources to show a relationship."],["provisional","Available now but subject to revision."],["limitation","A feature that restricts how a source supports a claim."]],"Compare sources within shared themes. State agreement, difference or explanation, then keep each source’s date, purpose and uncertainty attached to its evidence.","Two storm reports","A utility report explains repair operations; a municipal report records displaced residents. By theme, they agree on duration but reveal different consequences and institutional purposes.",["Add a fourth theme and justify why it changes the comparison.","Where might both official sources share the same blind spot?"]),
    d08:support("Practise diagnosis and priority on Harbourview, then complete the locked transfer independently.",[["counter-perspective","A credible competing view considered fairly."],["priority","The reasoned order in which action should occur."],["transfer","Applying learned reasoning to an unfamiliar case."]],"Evaluate a claim against all evidence, compare an alternative and trace priorities to stakeholder consequences. The assessed hospital case remains closed-book.","Transit card outage","If readers work offline but balance updates fail, restoring the database may lead. A rider-access perspective can still justify a temporary free-ride policy.",["Name a condition that would reverse your priority.","Which part of the reasoning transfers across all three choice contexts?"]),
    d09:support("Defend one causal link, state uncertainty and locate human oversight.",[["internet","Interconnected networks using shared protocols."],["web","Linked resources accessed through internet services."],["oversight","Human review with information and authority to intervene."]],"The internet, web, platforms and connected devices are related but distinct. Automated monitoring and recovery decisions need defined human checks.","Warehouse temperature alert","A sensor flags heat and automatically pauses shipping. A supervisor checks sensor agreement, product risk and false-alarm history before authorizing disposal.",["When could human review make a service less safe?","Write a threshold for when automatic action should be reversible."]),
    reflect:support("Name evidence, support used and one precise next target.",[["evidence","A specific product, explanation or observation supporting a judgment."],["independence","What a learner can decide or perform without help."],["next target","A precise action to improve on a fresh task."]],"Reflection identifies demonstrated learning, the support that helped and the next opportunity to show improvement. It is not itself an achievement mark.","Packet reasoning reflection","I can trace a route and identify the bottleneck in d03-runs. I used the glossary for protocol. Next I will explain packet loss versus delay on a fresh route without a frame.",["Which evidence best shows transfer rather than completion?","What support could you remove on the next attempt?"])
  }
};
